-d C:\Users\User Name\OneDrive\Escritorio\Verilog\Mis programas\mis programas\impl\gwsynthesis\mis programas.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NES
-cst C:\Users\User Name\OneDrive\Escritorio\Verilog\Mis programas\mis programas\src\mis programas.cst
-cfg C:\Users\User Name\OneDrive\Escritorio\Verilog\Mis programas\mis programas\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
